#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# 1. Hide the iOS warning (Safe to do on Windows/Linux)
kotlin.native.ignoreDisabledTargets=true

# 2. Suppress the Android SDK compatibility warning
android.suppressUnsupportedCompileSdk=35